### PR TITLE
FFI implementation

### PR DESCRIPTION
**Pull request by postsolar**
**Description of the change**

Clearly and concisely describe the purpose of the pull request. If this PR relates to an existing issue or change proposal, please link to it. Include any other background context that would help reviewers understand the motivation for this PR.

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Review by anttih — COMMENTED** [review]
Can you add a spago.yaml? Then we could merge this.

**Comment by anttih** [comment]
Oh this also needs `gen` which doesn't FFI.

**Comment by anttih** [comment]
`gen` is now in the package set.

**Comment by postsolar** [comment]
It has tests in it so I guess the workflows also should be added?

**Comment by anttih** [comment]
yeah we should add the CI config as well

**Review by anttih — APPROVED** [review]

**Pull request merged**
